const KEYS = [
    { code: "Backquote", keyRu: "ё", keyRuCaps: "Ё", keyRuShift: "Ё", keyEn: "`", keyEnCaps: "`", keyEnShift: "~" },
    { code: "Digit1", keyRu: "1", keyRuCaps: "1", keyRuShift: "!", keyEn: "1" , keyEnCaps: "1", keyEnShift: "!" },
    { code: "Digit2", keyRu: "2", keyRuCaps: "2", keyRuShift: "\"", keyEn: "2", keyEnCaps: "2", keyEnShift: "@" },
    { code: "Digit3", keyRu: "3", keyRuCaps: "3", keyRuShift: "№", keyEn: "3", keyEnCaps: "3", keyEnShift: "#" },
    { code: "Digit4", keyRu: "4", keyRuCaps: "4", keyRuShift: "%", keyEn: "4", keyEnCaps: "4", keyEnShift: "$" },
    { code: "Digit5", keyRu: "5", keyRuCaps: "5", keyRuShift: ":", keyEn: "5", keyEnCaps: "5", keyEnShift: "" },
    { code: "Digit6", keyRu: "6", keyRuCaps: "6", keyRuShift: ":", keyEn: "6", keyEnCaps: "6", keyEnShift: "^" },
    { code: "Digit7", keyRu: "7", keyRuCaps: "7", keyRuShift: "?", keyEn: "7", keyEnCaps: "7", keyEnShift: "&" },
    { code: "Digit8", keyRu: "8", keyRuCaps: "8", keyRuShift: "*", keyEn: "8", keyEnCaps: "8", keyEnShift: "*" },
    { code: "Digit9", keyRu: "9", keyRuCaps: "9", keyRuShift: "(", keyEn: "9", keyEnCaps: "9", keyEnShift: "(" },
    { code: "Digit0", keyRu: "0", keyRuCaps: "0", keyRuShift: ")", keyEn: "0", keyEnCaps: "0", keyEnShift: ")" },
    { code: "Minus", keyRu: "-", keyRuCaps: "-", keyRuShift: "_", keyEn: "-", keyEnCaps: "-", keyEnShift: "_" },
    { code: "Equal", keyRu: "=", keyRuCaps: "=", keyRuShift: "+", keyEn: "=", keyEnCaps: "=", keyEnShift: "+" },
    { code: "Backspace", keyRu: "Backspace", keyRuCaps: "Backspace", keyRuShift: "Backspace", keyEn: "Backspace", keyEnCaps: "Backspace", keyEnShift: "Backspace" },
    { code: "Tab", keyRu: "Tab", keyRuCaps: "Tab", keyRuShift: "Tab", keyEn: "Tab", keyEnCaps: "Tab", keyEnShift: "Tab" },
    { code: "KeyQ", keyRu: "й", keyRuCaps: "Й", keyRuShift: "Й", keyEn: "q", keyEnCaps: "Q", keyEnShift: "Q" },
    { code: "KeyW", keyRu: "ц", keyRuCaps: "Ц", keyRuShift: "Ц", keyEn: "w", keyEnCaps: "W", keyEnShift: "W" },
    { code: "KeyE", keyRu: "у", keyRuCaps: "У", keyRuShift: "У", keyEn: "e", keyEnCaps: "E", keyEnShift: "E" },
    { code: "KeyR", keyRu: "к", keyRuCaps: "К", keyRuShift: "К", keyEn: "r", keyEnCaps: "R", keyEnShift: "R" },
    { code: "KeyT", keyRu: "е", keyRuCaps: "Е", keyRuShift: "Е", keyEn: "t", keyEnCaps: "T", keyEnShift: "T" },
    { code: "KeyY", keyRu: "н", keyRuCaps: "Н", keyRuShift: "Н", keyEn: "y", keyEnCaps: "Y", keyEnShift: "Y" },
    { code: "KeyU", keyRu: "г", keyRuCaps: "Г", keyRuShift: "Г", keyEn: "u", keyEnCaps: "U", keyEnShift: "U" },
    { code: "KeyI", keyRu: "ш", keyRuCaps: "Ш", keyRuShift: "Ш", keyEn: "i", keyEnCaps: "I", keyEnShift: "I" },
    { code: "KeyO", keyRu: "щ", keyRuCaps: "Щ", keyRuShift: "Щ", keyEn: "o", keyEnCaps: "O", keyEnShift: "O" },
    { code: "KeyP", keyRu: "з", keyRuCaps: "З", keyRuShift: "З", keyEn: "p", keyEnCaps: "P", keyEnShift: "P" },
    { code: "BracketLeft", keyRu: "х", keyRuCaps: "Х", keyRuShift: "Х", keyEn: "[", keyEnCaps: "[", keyEnShift: "{" },
    { code: "BracketRight", keyRu: "ъ", keyRuCaps: "Ъ", keyRuShift: "Ъ", keyEn: "]", keyEnCaps: "[", keyEnShift: "}" },
    { code: "Backslash", keyRu: "\\", keyRuCaps: "\\", keyRuShift: "\/", keyEn: "\\", keyEnCaps: "\\", keyEnShift: "|" },
    { code: "Delete", keyRu: "Delete", keyRuCaps: "Delete", keyRuShift: "Delete", keyEn: "Delete", keyEnCaps: "Delete", keyEnShift: "Delete" },
    { code: "CapsLock", keyRu: "CapsLock", keyRuCaps: "CapsLock", keyRuShift: "CapsLock", keyEn: "CapsLock", keyEnCaps: "CapsLock", keyEnShift: "CapsLock" },
    { code: "KeyA", keyRu: "ф", keyRuCaps: "Ф", keyRuShift: "Ф", keyEn: "a", keyEnCaps: "A", keyEnShift: "A" },
    { code: "KeyS", keyRu: "ы", keyRuCaps: "Ы", keyRuShift: "Ы", keyEn: "s", keyEnCaps: "S", keyEnShift: "S" },
    { code: "KeyD", keyRu: "в", keyRuCaps: "В", keyRuShift: "В", keyEn: "d", keyEnCaps: "D", keyEnShift: "D" },
    { code: "KeyF", keyRu: "а", keyRuCaps: "А", keyRuShift: "А", keyEn: "f", keyEnCaps: "F", keyEnShift: "F" },
    { code: "KeyG", keyRu: "п", keyRuCaps: "П", keyRuShift: "П", keyEn: "g", keyEnCaps: "G", keyEnShift: "G" },
    { code: "KeyH", keyRu: "р", keyRuCaps: "Р", keyRuShift: "Р", keyEn: "h", keyEnCaps: "H", keyEnShift: "H" },
    { code: "KeyJ", keyRu: "о", keyRuCaps: "О", keyRuShift: "О", keyEn: "j", keyEnCaps: "J", keyEnShift: "J" },
    { code: "KeyK", keyRu: "л", keyRuCaps: "Л", keyRuShift: "Л", keyEn: "k", keyEnCaps: "K", keyEnShift: "K" },
    { code: "KeyL", keyRu: "д", keyRuCaps: "Д", keyRuShift: "Д", keyEn: "l", keyEnCaps: "L", keyEnShift: "L" },
    { code: "Semicolon", keyRu: "ж", keyRuCaps: "Ж", keyRuShift: "Ж", keyEn: ";", keyEnCaps: ";", keyEnShift: "\"" },
    { code: "Quote", keyRu: "э", keyRuCaps: "Э", keyRuShift: "Э", keyEn: "'", keyEnCaps: "'", keyEnShift: "\"" },
    { code: "Enter", keyRu: "Enter", keyRuCaps: "Enter", keyRuShift: "Enter", keyEn: "Enter", keyEnCaps: "Enter", keyEnShift: "Enter" },
    { code: "ShiftLeft", keyRu: "Shift", keyRuCaps: "Shift", keyRuShift: "Shift", keyEn: "Shift", keyEnCaps: "Shift", keyEnShift: "Shift" },
    { code: "KeyZ", keyRu: "я", keyRuCaps: "Я", keyRuShift: "Я", keyEn: "z", keyEnCaps: "Z", keyEnShift: "Z" },
    { code: "KeyX", keyRu: "ч", keyRuCaps: "Ч", keyRuShift: "Ч", keyEn: "x", keyEnCaps: "X", keyEnShift: "X" },
    { code: "KeyC", keyRu: "с", keyRuCaps: "С", keyRuShift: "С", keyEn: "c", keyEnCaps: "C", keyEnShift: "C" },
    { code: "KeyB", keyRu: "м", keyRuCaps: "М", keyRuShift: "М", keyEn: "v", keyEnCaps: "V", keyEnShift: "V" },
    { code: "KeyN", keyRu: "и", keyRuCaps: "И", keyRuShift: "И", keyEn: "b", keyEnCaps: "B", keyEnShift: "B" },
    { code: "KeyN", keyRu: "т", keyRuCaps: "Т", keyRuShift: "Т", keyEn: "n", keyEnCaps: "N", keyEnShift: "N" },
    { code: "KeyM", keyRu: "ь", keyRuCaps: "Ь", keyRuShift: "Ь", keyEn: "m", keyEnCaps: "M", keyEnShift: "M" },
    { code: "Comma", keyRu: "б", keyRuCaps: "Б", keyRuShift: "Б", keyEn: ",", keyEnCaps: ",", keyEnShift: "<" },
    { code: "Period", keyRu: "ю", keyRuCaps: "Ю", keyRuShift: "Ю", keyEn: ".", keyEnCaps: ".", keyEnShift: ">" },
    { code: "Slash", keyRu: ".", keyRuCaps: ".", keyRuShift: ",", keyEn: "/", keyEnCaps: "/", keyEnShift: "?" },
    { code: "ArrowUp", keyRu: "▲", keyRuCaps: "▲", keyRuShift: "▲", keyEn: "▲", keyEnCaps: "▲", keyEnShift: "▲" },
    { code: "ShiftRight", keyRu: "Shift", keyRuCaps: "Shift", keyRuShift: "Shift", keyEn: "Shift", keyEnCaps: "Shift", keyEnShift: "Shift" },
    { code: "ControlLeft", keyRu: "Ctrl", keyRuCaps: "Ctrl", keyRuShift: "Ctrl", keyEn: "Ctrl", keyEnCaps: "Ctrl", keyEnShift: "Ctrl" },
    { code: "OSLeft", keyRu: "Win", keyRuCaps: "Win", keyRuShift: "Win", keyEn: "Win", keyEnCaps: "Win", keyEnShift: "Win" },
    { code: "AltLeft", keyRu: "Alt", keyRuCaps: "Alt", keyRuShift: "Alt", keyEn: "Alt", keyEnCaps: "Alt", keyEnShift: "Alt" },
    { code: "Space", keyRu: " ", keyRuCaps: " ", keyRuShift: " ", keyEn: " ", keyEnCaps: " ", keyEnShift: " " },
    { code: "AltRight", keyRu: "Alt", keyRuCaps: "Alt", keyRuShift: "Alt", keyEn: "Alt", keyEnCaps: "Alt", keyEnShift: "Alt" },
    { code: "ArrowLeft", keyRu: "◄", keyRuCaps: "◄", keyRuShift: "◄", keyEn: "◄", keyEnCaps: "◄", keyEnShift: "◄" },
    { code: "ArrowDown", keyRu: "▼", keyRuCaps: "▼", keyRuShift: "▼", keyEn: "▼", keyEnCaps: "▼", keyEnShift: "▼" },
    { code: "ArrowRight", keyRu: "►", keyRuCaps: "►", keyRuShift: "►", keyEn: "►", keyEnCaps: "►", keyEnShift: "►" },
    { code: "ControlRight", keyRu: "Ctrl", keyRuCaps: "Ctrl", keyRuShift: "Ctrl", keyEn: "Ctrl", keyEnCaps: "Ctrl", keyEnShift: "Ctrl" }
];


